from pyspark.sql.functions import sum, desc, year, month

def revenue_by_category(df):

    """Calculate revenue generated by each category."""

    revenue_df = (
        df.groupBy("category")
        .agg(
            sum("sales_amount").alias("total_revenue")
        )
        .orderBy(desc("total_revenue"))
    )


    return revenue_df



def revenue_by_state(df):

    """Calculate revenue generated by each state"""

    revenue_df = (
        df.groupBy("state")
        .agg(
            sum("sales_amount").alias("total_revenue")
        )
        .orderBy(desc("total_revenue"))
    )

    return revenue_df


def revenue_by_month(df):

    revenue_df = (
        df.groupBy(
            year("order_date").alias("year"),
            month("order_date").alias("month")
        )
        .agg(
            sum("sales_amount").alias("total_revenue")
        )
        .orderBy("year", "month")
    )


    return revenue_df